-- Fresh-install schema for the moderated news-site comment system.
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  story_id text not null,
  author_name text not null,
  author_email text not null,
  content text not null,
  status text not null default 'PENDING_REVIEW',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  path text,
  author text,
  email text,
  url text,
  text text,
  approved boolean not null default false,
  constraint comments_status_check
    check (status in ('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'SPAM'))
);

alter table public.comments enable row level security;

drop policy if exists "public_select_approved" on public.comments;
create policy "public_select_approved" on public.comments
  for select using (status = 'APPROVED');

drop policy if exists "public_insert" on public.comments;
create policy "public_insert" on public.comments
  for insert with check (status = 'PENDING_REVIEW');

create index if not exists comments_status_idx on public.comments (status);
create index if not exists comments_story_id_idx on public.comments (story_id);
create index if not exists comments_created_at_idx on public.comments (created_at desc);
create index if not exists comments_story_status_created_idx
  on public.comments (story_id, status, created_at);
