-- Comments table for the news site
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  path text not null,
  author text,
  email text,
  url text,
  text text not null,
  approved boolean default false,
  created_at timestamptz default now()
);

alter table public.comments enable row level security;

drop policy if exists "public_select_approved" on public.comments;
create policy "public_select_approved" on public.comments
  for select using (approved = true);

drop policy if exists "public_insert" on public.comments;
create policy "public_insert" on public.comments
  for insert with check (true);

create index if not exists comments_path_created_at_idx
  on public.comments (path, created_at desc);